name: galaxy_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.20+21

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^0.9.2+6
  http: ^0.12.2
  provider: ^4.3.3
  dio: ^3.0.10
  dio_http_cache: ^0.2.6
  dropdown_search: ^0.4.8
  searchable_dropdown: ^1.1.3

  flutter_volume_slider: ^1.0.6
  flag: ^3.1.0
  dotenv: ^2.0.0
  shared_preferences: <=2.0.3
  synchronized: ^2.1.0+1
  slide_to_confirm: ^0.0.7
  mqtt_client: ^7.2.1
  jwt_decode: ^0.2.0
  mdi: ^3.0.0
  flutter_logs: #^2.1.4
    git:
      url: https://github.com/igala/flutter_logs.git
      ref: 2.1.4-2
    #path: ../../flutter_logs

  system_info: ^0.1.3
  disk_space: ^0.0.3
  archive: ^2.0.13
  flutter_email_sender: ^4.0.0
  fluttertoast: ^7.1.8
  easy_localization: ^2.3.3
  package_info: ^0.4.0+16
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_remote_config: ^0.6.0
  firebase_crashlytics: ^0.4.0+1

  wakelock: ^0.2.1+1
  flutter_fgbg: ^0.0.1
  url_launcher: ^5.7.10
  connectivity_plus: ^0.8.1
  phone_state_i: ^0.0.3
#    path: ../../Documents/GitHub/PhoneCallState-fork
  logcat: #^1.0.2
    git:
      url: https://github.com/igala/logcat.git
#    path: ../../Documents/GitHub/logcat-fork/
  flutter_foreground_plugin: #^0.6.0
    git:
      url: https://github.com/igala/flutter_foreground_service_plugin.git
    #https://github.com/shivanshtalwar0/flutter_janus_client.git
      ref: 0.6.0_taskRemovedFix
  #    path: ../../Documents/Github/flutter_foreground_service_plugin/
  dots_indicator: ^1.2.0
  flutter_audio_manager: ^0.2.3
  readmore: ^1.0.1

  janus_client: #^0.0.4
    git:
      url: https://github.com/igala/flutter_janus_client.git
      #https://github.com/shivanshtalwar0/flutter_janus_client.git
      ref: 0.0.4+5
      #path: ../../Documents/Github/flutter_janus_client-fork/


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^4.0.2+3

  sentry_flutter: ^4.0.6

  device_info: ^1.0.0

  new_version: ^0.0.6


dev_dependencies:
  rename: ^1.3.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

  # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/graphics/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/graphics/logo.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/graphics/
    - assets/json/
    - assets/translations/
    - assets/res/t_and_c_en.txt
    - assets/res/t_and_c_he.txt
    - assets/res/t_and_c_ru.txt

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
