name: galaxy_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.2+78

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  scrollable_positioned_list: ^0.3.5
  flutter:
    sdk: flutter
  path_provider: ^2.0.14
  flutter_appauth: ^4.2.1
  http: ^0.13.5
  provider: ^6.0.4
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  dropdown_search: ^5.0.3
  searchable_dropdown: ^1.1.3
  flutter_linkify: ^5.0.2
 # flutter_volume_slider: ^1.0.6
  flag: ^6.0.0
  dotenv: ^4.0.1
  headset_connection_event: ^3.1.0
  shared_preferences: ^2.0.15
  synchronized: ^3.0.0+3
  slide_to_confirm: ^1.1.0
  mqtt5_client: #^3.3.3
      git:
        url: https://github.com/igala/mqtt5_client.git
        ref: 2.1.0_flutter_3.3.7
    #path: ../../mqtt5_client
  jwt_decode: ^0.3.1
  mdi: ^4.0.0
  flutter_html: ^3.0.0-alpha.6
  flutter_logs: ^2.1.10
#    git:
#      url: https://github.com/igala/flutter_logs.git
#      ref: 2.1.4-3
#    path: ../../flutter_logs

  system_info: ^1.0.1
  disk_space: ^0.2.1
  archive: ^3.3.4
  flutter_email_sender: ^5.2.0
  fluttertoast: ^8.1.1
  easy_localization: ^3.0.1
#    path: /Users/shidur/Downloads/easy_localization-develop
  package_info: ^2.0.2
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  firebase_remote_config: ^3.0.6
  firebase_crashlytics: ^3.0.6

  wakelock: ^0.6.2
  flutter_fgbg: ^0.2.1
  url_launcher: ^6.1.6
  connectivity_plus: ^3.0.2
  phonecall_state:
    git:
      url: https://github.com/igala/phonecall_state.git
#      ref: 0.0.3.1
#    path: /Users/shidur/PhoneCallState
  logcat: ^1.0.2
#    git:
#      url: https://github.com/igala/logcat.git
#    path: ../../Documents/GitHub/logcat-fork/
  flutter_foreground_plugin: #^0.6.0
    git:
        url: https://github.com/igala/flutter_foreground_service_plugin.git
    #https://github.com/shivanshtalwar0/flutter_janus_client.git
        ref: 0.8.0.2
#      path: /Users/shidur/flutter_foreground_service_plugin/
  dots_indicator: ^2.1.0
  flutter_audio_manager: #^0.2.3.1
    git:
      url: https://github.com/igala/flutter_audio_manager.git
      ref: 0.2.3.1
  readmore: ^2.2.0
  permission_handler: ^11.0.1
  janus_client: #^0.0.4
        git:
          url: https://github.com/igala/flutter_janus_client.git
#          #https://github.com/shivanshtalwar0/flutter_janus_client.git
          ref: 0.0.4+16
#    path: ../../flutter_janus_client


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.6.0

  sentry_flutter: ^6.16.0

  device_info: ^2.0.3

  icon_badge: ^1.0.0
  new_version: ^0.3.1
  flutter_app_version_checker: ^0.3.2
  webview_flutter: ^3.0.4
  sdp_transform: ^0.3.2

dev_dependencies:
  rename: ^2.0.1
  flutter_test:
    sdk: flutter


  # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/graphics/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/graphics/logo.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/graphics/
    - assets/json/
    - assets/ca/
    - assets/translations/
    - assets/res/t_and_c_en.txt
    - assets/res/t_and_c_he.txt
    - assets/res/t_and_c_ru.txt

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
